server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.myappserver.model
  mapper-locations: classpath:mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.myappserver.controller
  paths-to-match: /api/**

huaweicloud:
  obs:
    ak: 8WIP5EXT7MMTBSRNIQZG # ${OBS_ACCESS_KEY}  # 从环境变量获取
    sk: XY87GFANQsYZo36NadWe3C983xHnN0TbA27aCNuq # ${OBS_SECRET_KEY}  # 从环境变量获取
    endpoint: https://obs.cn-south-1.myhuaweicloud.com
    bucketName: my-app